spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postdb
    username: postgres
    password: PkNLm@#2357
  jpa:
    properties:
      hibernate:
        "[format_sql]": true
      jdbc:
        "[batch_size]": 30
      "[order_inserts]": true
      "[order_deletes]": true
      "[generate_statistics]": true
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    web: debug
    "[com.hangout.core]": trace
  # traceID and spanId are predefined MDC keys - we want the logs to include them
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318

minio:
  url: http://localhost:9000
  accessKey: sy22NKhjmHHCxGkSxn4h
  secretKey: iBfNydMCIC1KT4qBAj8RB8kaMLpXZ5yI41CTf6Ox

hangout:
  kafka:
    content:
      topic: content
    heart:
      topic: hearts
      maxPollRecords: 100
      fetchMinBytes: 1024
      fetchMaxWaitMs: 10000
  auth-service:
    url: http://localhost:5011
  media:
    upload-bucket: hangout-upload-path
  allowed-origins:
    url: http://localhost:3000,
  page-length: 25
  log:
    path: /home/soumalya/Development/Hangout/core-services/hangout-post-api/logs
