server:
  port: 5013
  servlet:
    context-path: /post
spring:
  application:
    name: post
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${CLUSTER_URL}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  jpa:
    properties:
      hibernate:
        "[format_sql]": true
    hibernate:
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS

# All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus, health
  # For Exemplars to work we need histogram buckets
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    web: error
    sql: error
    "[org.springframework.security]": error
    "[com.hangout.core]": trace
    # traceID and spanId are predefined MDC keys - we want the logs to include them
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

hangout:
  loki-server:
    url: ${LOKI_SERVER}
  tempo-server:
    url: ${TEMPO_SERVER}
  log:
    path: ${LOG_DIR}
