spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/posts
    username: postgres
    password: PkNLm@#2357
  jpa:
    properties:
      hibernate:
        "[format_sql]": true
      jdbc:
        "[batch_size]": 30
      "[order_inserts]": true
      "[order_deletes]": true
      "[generate_statistics]": true
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    web: debug
    "[com.hangout.core]": trace
  # traceID and spanId are predefined MDC keys - we want the logs to include them
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317

aws:
  region: ap-south-1

hangout:
  kafka:
    content:
      topic: content
    heart:
      topic: hearts
      maxPollRecords: 1500
      fetchMinBytes: 3072
      fetchMaxWaitMs: 10000
  auth-service:
    url: http://localhost:80/auth-api/v1
  media:
    upload-bucket: hangout-uploaded
  allowed-origins:
    url: http://localhost:5137,
  page-length: 25
  log:
    path: /home/soumalya/Development/Hangout/core-services/hangout-post-api/logs
  address-api:
    base-url: https://api.geoapify.com
