spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postdb
    username: postgres
    password: PkNLm@#2357
  jpa:
    properties:
      hibernate:
        "[format_sql]": true
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    web: debug
    "[com.hangout.core]": trace
  # traceID and spanId are predefined MDC keys - we want the logs to include them
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

# All traces should be sent to latency analysis tool
management:
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus, health
  # For Exemplars to work we need histogram buckets
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

minio:
  url: http://localhost:9000
  accessKey: IevColMiX5eBAZUPmfN6
  secretKey: G8HC3uphX1TlDDYSxtjTrFSVdRe95XJXV2IhqEYg

hangout:
  auth-service:
    url: http://localhost:5011
  media:
    upload-path: /media/soumalya/793f3da3-8908-48a8-a4ce-a638275951fa/hangout-upload-path
  otel-collector:
    url: http://localhost:4318
  log:
    path: /home/soumalya/Development/Hangout/core-services/hangout-post-api/logs
